# -*- coding: utf-8 -*-
"""nbaWebScrape.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lETBP2EzK3KWBsdrIo0cTFjueumfr73U
"""

from bs4 import BeautifulSoup
import pandas as pd
import requests
import math
import time
import random
from datetime import date
import csv

url = 'https://www.basketball-reference.com/leagues/NBA_2022_totals.html'
headers = {'User-Agent': 'Mozilla/5.0'}
source = requests.get(url, headers = headers)

# source.status_code   # 200 connect sucess

soup = BeautifulSoup(source.content, 'html.parser')
my_list = []

for link in soup.find_all('a'):
  #print(link)
  my_list.append(link.get('href'))

player_list = []
filter_player = "/players/"
with_player = [x for x in my_list if x.startswith(filter_player)]

player_list = with_player[5:476]

updated_players = []

for each in range(len(player_list)):
  updated_players.insert(each,player_list[each].strip(".html"))

stats_new = []
headers_players = []     #No score on the refernce website  
headers_players = ['Name','Age', 'Tm', 'Opp', 'Date', 'Score', 'Wflag', 'PTS', 'FANP', 'MP', 'FG', 'FGA', 'FGP', '3P', '3PA', '3PP','FT', 'FTA', 'FTP','ORB','DRB','TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF' ]   # FANP FANTSY POINT AT THE END

header_website = ['Games_d','Date','Age','Tm','_d','Opp','Wflag','GS_d','MP','FG','FGA','FG%','3P','3PA','3P%','FT','FTA','FT%','ORB','DRB','TRB','AST','STL','BLK','TOV','PF','PTS','GmSc_d','eff_d']
# len(header_website)

def fpCalc(threePFG, twoPFG, FTM, ORB, DRB, AST, BLK, STL, TOV):
  totalFP = 0
  totalFP = (int(threePFG)*3) + (int(twoPFG)*2) + (int(FTM)*1) + ((int(ORB)+int(DRB))*1.2) + (int(AST)*1.5) + (int(BLK)*3) + (int(STL)*3) + (int(TOV)*-1)
  return totalFP

def winCheck(winStatus):
  if 'W' in winStatus:
    return '1'
  if 'L' in winStatus:
    return '0'

headers_players_stats_new = []
temp = []
data_holder = []
size = 1
s_new = pd.DataFrame()
name = ''
for i in range(0,len(updated_players)):
  url_each_player = "https://www.basketball-reference.com" + updated_players[i] + "/gamelog/2022"
  # print(url_each_player) 
  source_n = requests.get(url_each_player)
  soup_n = BeautifulSoup(source_n.content, 'html.parser')
  table = soup_n.find('table', id='pgl_basic')
  rows = table.findAll('tr')[1:]
  reason = soup_n.find('td', {"data-stat": "reason"})
  player_stats = [[td.getText() for td in rows[i].findAll('td')] for i in range(len(rows))]
  stats_new = player_stats[27:]

  for a in soup_n.findAll("div", {"id": "info"}):
    for x in a.findAll("h1", {"itemprop": "name"}):
      for y in x.findAll("span"):
        z = str(y.text)
        z = z[:-17]
        name = z
        break
      break
    break
 
  count = len(player_stats)
  for x in range(0,count):

    stat = player_stats[x]
    if not stat:
      continue
    elif str(player_stats[x][7])=='Inactive' or str(player_stats[x][7])=='Did Not Play' or str(player_stats[x][7])=='Did Not Dress' or str(player_stats[x][7])=='Not With Team' or str(player_stats[x][7])=='Player Suspended':
      temp = [name, stat[2][:2], stat[3], stat[5], stat[1], 'NULL', winCheck(str(stat[6])), 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL'
              , 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL']
    else:
      fp_tot = fpCalc(stat[12], stat[9], stat[15], stat[18], stat[19], stat[21], stat[23], stat[22], stat[24])
      temp = [name, stat[2][:2], stat[3], stat[5], stat[1], 'NULL', winCheck(str(stat[6])), stat[26], fp_tot, stat[8], stat[9], stat[10], stat[11], stat[12]
              , stat[13], stat[14], stat[15], stat[16], stat[17], stat[18], stat[19], stat[20], stat[21], stat[22], stat[23], stat[24], stat[25]]

    headers_players_stats_new.append(temp)
    # time.sleep(random.randint(0, 3))

display_games = pd.DataFrame(headers_players_stats_new, columns=headers_players)
display_games

today = date.today()
today = str(today)+".csv"
# display_games.to_csv('temp.csv')                            #converting to csv file
display_games.to_csv('/Users/bryanthoang/Desktop/NBA_Python/' + today, index=False)      #some pathing to save the file