# Generated by Django 3.1 on 2021-11-26 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('team1_is_winner', models.BooleanField()),
                ('score', models.CharField(max_length=8)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='home.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='home.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pts', models.IntegerField()),
                ('fanp', models.IntegerField()),
                ('mp', models.TimeField()),
                ('fg', models.IntegerField()),
                ('fga', models.IntegerField()),
                ('fgp', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('tp', models.IntegerField()),
                ('tpa', models.IntegerField()),
                ('tpp', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('ft', models.IntegerField()),
                ('fta', models.IntegerField()),
                ('ftp', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('orb', models.IntegerField()),
                ('drb', models.IntegerField()),
                ('trb', models.IntegerField()),
                ('ast', models.IntegerField()),
                ('stl', models.IntegerField()),
                ('blk', models.IntegerField()),
                ('tov', models.IntegerField()),
                ('pf', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.player')),
            ],
        ),
    ]
