# Generated by Django 3.1 on 2021-11-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_game_playergame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergame',
            name='mp',
            field=models.DurationField(),
        ),
    ]
