# Generated by Django 3.1 on 2021-11-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211125_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergame',
            name='fgp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='playergame',
            name='ftp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='playergame',
            name='tpp',
            field=models.FloatField(null=True),
        ),
    ]
