# Generated by Django 3.1 on 2021-12-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211126_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergame',
            name='fanp',
            field=models.FloatField(),
        ),
    ]
